src/main/resources/application.yml

This PR fix typo error on environment variables related to splitter and tkm queues

fix: Environment variable names

---

src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/ApplicationInstrumentSplitterFlow.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationBulkEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationInstrumentAdded.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationInstrumentDeleted.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationInstrumentEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationBulkEventSplitter.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationInstrumentEventPublisher.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/common/cloudevent/CloudEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/common/cloudevent/CloudEventType.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/ApplicationEventIntegrationFlowConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/TkmIntegrationFlowConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/properties/IntegrationFlowKafkaProperties.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/ports/rest/KafkaRestController.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/ports/rest/KafkaRestControllerImpl.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/TkmSplitterFlow.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/events/TokenManagerCardChanged.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerCardEventPublisher.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/TestUtils.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationBulkEventSplitterTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationEventSplitterFlowTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationInstrumentEventPublisherTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerCardEventPublisherTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerWalletEventTkmSplitterFlowTest.java
src/test/resources/application-test.yml

This PR adds application events splitting

feat: [RTD-790] Application instrument event splitter 

---

.devops/deploy-pipelines.yml
.github/workflows/release.yml
manifests/deployment.yml
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/ApplicationInstrumentSplitterFlow.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationBulkEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationInstrumentAdded.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationInstrumentDeleted.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationInstrumentEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationBulkEventSplitter.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationInstrumentEventPublisher.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/common/cloudevent/CloudEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/common/cloudevent/CloudEventType.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/ApplicationEventIntegrationFlowConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/TkmIntegrationFlowConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/properties/IntegrationFlowKafkaProperties.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/ports/rest/KafkaRestController.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/ports/rest/KafkaRestControllerImpl.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/TkmSplitterFlow.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/events/TokenManagerCardChanged.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerCardEventPublisher.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/TestUtils.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationBulkEventSplitterTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationEventSplitterFlowTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationInstrumentEventPublisherTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerWalletEventTkmSplitterFlowTest.java
src/test/resources/application-test.yml

Deploy UAT

---

.devops/deploy-pipelines.yml
.github/workflows/release.yml
manifests/deployment.yml
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/ApplicationInstrumentSplitterFlow.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationBulkEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationInstrumentAdded.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationInstrumentDeleted.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationInstrumentEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationBulkEventSplitter.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationInstrumentEventPublisher.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/common/cloudevent/CloudEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/common/cloudevent/CloudEventType.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/ApplicationEventIntegrationFlowConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/TkmIntegrationFlowConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/properties/IntegrationFlowKafkaProperties.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/ports/rest/KafkaRestController.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/ports/rest/KafkaRestControllerImpl.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/TkmSplitterFlow.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/events/TokenManagerCardChanged.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerCardEventPublisher.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/TestUtils.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationBulkEventSplitterTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationEventSplitterFlowTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationInstrumentEventPublisherTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerWalletEventTkmSplitterFlowTest.java
src/test/resources/application-test.yml

This PR promotes this microservice to PROD environment

Deploy to PROD

---

src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/events/TokenManagerCardChanged.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/events/TokenManagerWalletChanged.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerWalletEventSplitterTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerWalletEventTkmSplitterFlowTest.java

This PR fix ISO8601 parse without throwing exceptions

fix: iso parse

---

src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/events/TokenManagerWalletChanged.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/events/TkmDateDeserializerTest.java

This PR fix tkm date event parse by providing a parser to custom date formate with a fallback to ISO8601.

fix: tkm date deserialization

---

src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerWalletEventSplitterTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerWalletEventTkmSplitterFlowTest.java

fix: timestamp tkm event

---

helm/rtd/.helmignore
helm/rtd/Chart.yaml
helm/rtd/values-dev.yaml
helm/rtd/values-prod.yaml
helm/rtd/values-uat.yaml
helm/rtd/values.yaml
pom.xml
src/main/resources/application.yml

This PR add helm chart configuration to microservice

chore: [RTD-905] add helm chart and actuator

---

src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/ApplicationInstrumentSplitterFlow.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationBulkEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationBulkEventSplitter.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationInstrumentEventPublisher.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/common/cloudevent/CloudEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/ApplicationEventIntegrationFlowConfiguration.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationBulkEventSplitterTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationEventSplitterFlowTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationInstrumentEventPublisherTest.java

This PR adds correlationId support when splitting message from applications

feat: [RTD-1248] Add correlationId to inbound and outbound event

---

Dockerfile

Bump Application Insights version.

chore: [RTD-1221] Bump Application Insights agent version

---

src/main/resources/application.yml

This PR fix wrong env variable name for partition count

fix: partition count env variable

---

.devops/cstar-rtd-code-review-pipelines.yml
src/main/resources/application.yml

fix: partition count env variable (#22)

---

Dockerfile
src/main/resources/application.yml

* [RTD-1221] bump Application Insights agent version
* [RTD-1221] bump Application Insights agent version
* fix partition count env variable (#22)
[RTD-1221]: https://pagopa.atlassian.net/browse/RTD-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1221]: https://pagopa.atlassian.net/browse/RTD-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: partition count env variable (#22) (#23)

---

.devops/cstar-rtd-code-review-pipelines.yml
src/main/resources/application.yml

Producer partitioned to UAT

---

helm/rtd/values.yaml

fix: [RTD-1457] Fix appinsights problem

---

.github/workflows/release.yml

chore: [RTD-1532] update checkout version

---

.github/CODEOWNERS
Dockerfile
pom.xml
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/ApplicationInstrumentSplitterFlow.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationBulkEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationInstrumentEventPublisher.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/common/cloudevent/CloudEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/CommonConsumerConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/events/TokenManagerCardChanged.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerCardEventHandler.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationEventSplitterFlowTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationInstrumentEventPublisherTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerCardEventPublisherTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerWalletEventTkmSplitterFlowTest.java

This PR proposes to upgrade to spring boot 3
Version bumps:
| package | old version | new version |
| --- | --- | --- |
| java | 11 | 17 |
| spring boot | 2.7.4 | 3.0.6 |
| spring cloud | 2021.0.4 | 2022.0.2 |
| snakeyaml | 1.32 | 2.0 |
| build image | maven:3.8.5-openjdk-17 | maven:3.9.0-amazoncorretto-17 | 
| run image | amazoncorretto:17-alpine-jdk | amazoncorretto:17.0.7-al2023-headless |
| appinsights | 3.4.8 | 3.4.11 |
| mockito-inline | 4.8.1 | 5.2.0 |
removed dependencies:
- org.springframework.cloud:spring-cloud-stream-test-support
- org.springframework.cloud:spring-cloud-stream-test-binder

fix: [RTD-1591] upgrade spring boot 3

---

.github/workflows/anchore.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml
Dockerfile
pom.xml

fix: [RTD-1740] pinning sha on actions and docker images

---

.github/CODEOWNERS
.github/workflows/anchore.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml
Dockerfile
pom.xml
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/ApplicationInstrumentSplitterFlow.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/events/ApplicationBulkEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationInstrumentEventPublisher.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/common/cloudevent/CloudEvent.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/CommonConsumerConfiguration.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/events/TokenManagerCardChanged.java
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerCardEventHandler.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationEventSplitterFlowTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/app/splitter/ApplicationInstrumentEventPublisherTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerCardEventPublisherTest.java
src/test/java/it/gov/pagopa/rtd/ms/pieventprocessor/tkm/splitter/TokenManagerWalletEventTkmSplitterFlowTest.java

fix: Promotion to UAT

---

.releaserc.json
pom.xml

This PR proposes to add the releaserc.json file to fix the semantion release action. Plus realign pom to base version

fix: [RTD-1796] add releaserc.json file

---

.releaserc.json
pom.xml

fix: Promotion to UAT - add releaserc.json

---

Dockerfile
helm/rtd/values.yaml
pom.xml

* [RTD-1808] run container as non-root
* [RTD-1808] bump pom version
[RTD-1808]: https://pagopa.atlassian.net/browse/RTD-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RTD-1808]: https://pagopa.atlassian.net/browse/RTD-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Promotion to UAT - run container as non-root

---

.releaserc.json
Dockerfile
helm/rtd/values.yaml
pom.xml

fix: Promotion to Prod - run as non-root user

---

Dockerfile
helm/rtd/values.yaml
pom.xml

This PR proposes to update spring boot and its dependencies
package | old version | new version
-- | -- | --
spring boot | 3.0.6 | 3.1.2
spring cloud | 2022.0.2 | 2022.0.3
snakeyaml | 2.0 | 2.1
run image | amazoncorretto:17.0.7-al2023-headless | amazoncorretto:17.0.8-alpine3.18
appinsights | 3.4.14 | 3.4.15

fix: [RTD-1880] update spring dependency and pom version

---

pom.xml

package | old version | new version
-- | -- | --
spring boot | 3.1.2 | 3.1.3
kafka | 3.4.1 | 3.5.1

fix: [RTD-1880] upgrade spring and kafka

---

.releaserc.json
Dockerfile
helm/rtd/values.yaml
pom.xml

fix: Promotion to prod - upgrade spring boot

---

helm/rtd/values.yaml
src/main/java/it/gov/pagopa/rtd/ms/pieventprocessor/configuration/TkmIntegrationFlowConfiguration.java
src/main/resources/application.yml
src/test/resources/application-test.yml

chore: [RTD-1933] Disable tkm integration flow
